### PR TITLE
min php on composer.json

### PR DESCRIPTION
**Pull request by geminorum**

### CODE REVIEW

**Comment by Fonata** [comment]
Thank you, publishing the PHP requirement is valuable. 

Now, the `ParseCsv\tests` is only defined in the ``autoload-dev`` section. 

@geminorum Can you explain why you removed the tests namespace?  
@susgo do you think there is any reason to have it in both `autoload` **and** `autoload-dev`?

**Comment by susgo** [comment]
@Fonata No, we changed it to `autoload-dev`.

**Comment by geminorum** [comment]
> Classes needed to run the test suite should not be included in the main autoload rules to avoid polluting the autoloader in production and when other people use your package as a dependency.

from: [composer docs](https://getcomposer.org/doc/04-schema.md#autoload-dev)

**Comment by Fonata** [comment]
Ok, perfect. Thanks to both of you! 

I'll give the other maintainers a chance to review this. I'll merge this on April 10 at the earliest.

**Comment by williamknauss** [comment]
Looks good to me!

**Comment by Fonata** [comment]
@arturock indeed, it's not supported. Today, I'd never allow it on a production server.

PHP 5.5 is the actual technical requirement for this library (even though it is just the tests that require it). For now I tend to see little in forcing people to upgrade PHP if it's an isolated environment. We have such an environment on a Raspberry Pi running a PHP-based kiosk application that's almost never connected to the web or even local network.

**Pull request merged**
