### PR TITLE
Incorrect unparsing data when empty cells

### PR DESCRIPTION
**Pull request by wellic**

### CODE REVIEW

**Comment by wellic** [comment]
This PR has been blocked by Travis tests. Can someone unlock it? It contains the very useful patch.

**Comment by shazahm1** [comment]
@wellic 

Your code is bugged.

``` php
		// create data
		foreach ( $data as $key => $row ) {

			foreach ( $fields as $key => $fieldname ) {

				$value   = isset( $row[ $fieldname ] ) ? $row[ $fieldname ] : NULL;
				$entry[] = $this->_enclose_value( $value, $delimiter );
			}

			$string .= implode( $delimiter, $entry ) . $this->linefeed;
			$entry  = array();
		}
```

The second/inner `foreach` you are using the `$key` variable name overwriting the first/outer `foreach` loop variable `$key`. The second/inner `foreach` you should use a different name for the `$key` variable.

**Comment by wellic** [comment]
Fixed

**Comment by shazahm1** [comment]
@wellic Code looks good, Travis is still failing due to error in its config. @williamknauss would have to fix that.

**Comment by Fonata** [comment]
@wellic can you give example code (or example file) that causes problems with the original `unparse` function? Please write what you observed and what you expected instead. 

I'd like to document your expectation as PHPUnit code for automated testing.

Thanks!

**Comment by wellic** [comment]
Old commits

**Pull request closed without merging**
