### PR TITLE
refactor / improve construct and parse method

### PR DESCRIPTION
**Pull request by susgo**
This pull request is WIP. Feel free to close it because it needs another way of calling construction and parse method. 

I was confused by the duplications of setting properties in both methods. Another solution than the one I introduce here is to call constructor in the parse method but then the parse method could also be static.

Sorry, if I miss basics. I'm very interested in your feedbacks.

### CODE REVIEW

**Comment by Fonata** [comment]
Initialization with an array looks cool to the JavaScript/jQuery developer in me. 

For existing users of this project, backwards compatibility is a must. Therefore, please don't change the `__construct` or `parse` call signatures. Instead, you could write a new method that sets and validates all class fields from an array.

From an software architecture point of view, inheriting from a class called Object feels not expressive enough and weird to me.

What is the actual problem/DX issue you would like to solve?

**Comment by susgo** [comment]
I think construction by array is not really the clean way or best practice but the way to hold all functionalities and to keep it short. And it's kind of charming. 😊 

You are right with the name. I dislike it this morning too. :confounded:

My intention is maybe something like clean code - only in my point of view. And I thought that this change is maybe possible with version upgrade. 

Sure I am wrong: but why do I need a class definition if almost every method can set and (and thats my point) overwrite properties without warning if the right way for the user would be instantiating a new object (I am exaggerating, I know).  In my opinion it is difficult to understand and not intuitiv. It also duplicates code (can be solved with new setter function - that's right). I would also like to reduce the nullable paramter transfers. 

I think the other way would be (with only little changes to the actual code) all that could be and should be static calls. 

Sorry, I‘m sure thats all beginners stuff. But this is a very friendly and open community so I thought we could discuss this. :flushed: But feel free to close it without commenting. 

Also, I'm sorry for my bad englisch so maybe it is not clear what I mean.

**Comment by Fonata** [comment]
@susgo you are absolutely right that learning how to best use ParseCsv is harder than it should be because of all the optional parameters. 

I love putting time into the project, and seeing how beginners (maybe including you) are confused lead me to thinking it can be done better, too. But: I don't want to break things for people. I consider the project status of ParseCsv to be rather mature (there are [younger libraries for PHP and CSV](https://github.com/search?q=csv+php) around). I see my role also in keeping this repo working for older projects to use. 

Innovation is certainly welcome, though! It shouldn't break anyone's code if we add new functions and class fields together as the ParseCsv community. I'm glad that enthusiasts like you take part in this project. No need to worry about your English or programming skills, both are fine.

**Comment by susgo** [comment]
Okay, thanks. Then I close this request here.

**Comment by susgo** [comment]
This should be compatible for old versions.

**Comment by Fonata** [comment]
How should we call a person who downloads this project, never changes it and just uses it? Consumer?
 Pure user? Mmmh, opinions welcome. 😕 

I like this version much better, a creative approach. Here are some concerns I have:
- `Object` is a really generic term, and [leads to failed tests as it appears to be reserved](https://travis-ci.org/parsecsv/parsecsv-for-php/builds/344807931?utm_source=github_status&utm_medium=notification). Please suggest a better base class name.
- the function `parse` is new overloaded, but PHP doesn't support overloading. I suspect that certain PHP configurations will throw warnings because of this.
- while the code may turn out to be easier to use for pure users, I personally feel like the development experience for enhancing ParseCsv gets much harder with this pull request, as more levels are added.

I don't think this is a dead end, but it needs careful thought and implementation.

@susgo if you like you can also take on the task of splitting the large class into `ParserTrait` and `WriterTrait` files. Maybe there should also be a `SortAndConditionalTrait`? Just a suggestion, you're free to choose what seems interesting to you. ☺️

**Comment by susgo** [comment]
@Fonata Okay, that is right - it is buggy at the moment, but WIP says this. I always only use some short time episodes (composer updates on my main project) to improve this one here.

In my opinion at the moment we are free to rename the parse-method defined in the Csv-Class, something like read maybe. Object was also bad idea.... Sorry. 

But I understand your last hint. It's your project or you are one of the core team members and you do not like the direction of this pull request. That's okay. So again, I close this here.

**Comment by Fonata** [comment]
No hard feelings on my side. Sorry if I upset you. You're welcome here.

It's not my project, I see it as a community effort. I only started working on it [a few weeks ago](https://github.com/parsecsv/parsecsv-for-php/pull/102#issuecomment-341824160).

**Comment by susgo** [comment]
No, you don't upset me but some of your points are confusing for me. And all in all I prefer sometimes hard words instead of beat about the bush. In architecture and technical things but also in project vision things. So just a short: 'this is not the vision of the project that I have' will save our time. 

In any case, this is not meant badly. We have only different visions. My vision was to use the opportunity to fully rethink from user and developer experience.

**Comment by Fonata** [comment]
Thanks for your feedback. I'll propose a CONTRIBUTING.md in a separate pull request.

**Comment by susgo** [comment]
Means?

**Comment by Fonata** [comment]
Well, in that file I'll summarize some of the points we talked about here and contributors like you can improve it or say they disagree. In the later case, I wouldn't merge the proposal.

I don't want to waste anyone's time, so if that guide helps communicating what can and cannot be merged: perfect. I'm actually surprised that this project woke up lately. It more or less slept during the last 2-3 years.

**Comment by Fonata** [comment]
This is sort of my first open-source project, so I am learning together with everyone.

**Comment by susgo** [comment]
I love contributing and sharing code because I think that's the future and best way to learn. 

Wish you good luck with this in the future!

**Comment by Fonata** [comment]
Same here! 

Thanks for your hard work in this project. Feel free to open issues and pull requests. I know you had good reasons, which I mostly share, but I'm sad every time a pull request is closed without merging - even if it's for the best for the project in the long run.

**Comment by susgo** [comment]
That's a matter of opinion. I think the traits and enums will bring a harder level for developers too. So maybe you should think about it and I shouldn't do that for this project.

**Pull request closed without merging**
