### PR TITLE
Add a namespace

### PR DESCRIPTION
**Pull request by yohanlebret**

### CODE REVIEW

**Comment by williamknauss** [comment]
@jimeh,
Since ultimately this is your project what namespace would you like to use?

**Comment by jimeh** [comment]
@williamknauss I'm gonna sound a bit idiotic here, but namespaces came into being after I'd mostly stopped using PHP. As such I'm not familiar with what's considered best practices in terms of namespace usage aside from some random Googling.

So we might be better off with you taking the final decision on it, but I do have a couple of questions/notes:

- Is a namespace needed for a library that consists of only one class? (I'm gonna assume yes based on PSR-4's guidelines)
- As far as I can I've understood, this PR would mean usage would look something like this:

        $csv = new \Parsecsv\PhpParseCsv\parseCSV();

  Which to me looks like a lot of needless repetition. Wouldn't something like this be better?

        $csv = new \ParseCSV\CSV();
        // or
        $csv = new \ParseCSV\Parser();

  But it still has some repetition, and not sure the `Parser()` one makes much sense unless there's also a `Builder()` used for creating CSV output. Or maybe have `\ParseCSV\CSV` as the class, and have `\ParseCSV\parse()` and other functions exposed that return a `\ParseCSV\CSV` instance? Maybe I'm just going too deep down the rabbit whole though.

Ultimately though, as long as the usage pattern is sensible, and not silly long with effectively the same words repeated three or more times, I don't really mind too much how we name it :)

**Comment by Nonoki** [comment]
If there is a namespace, it's possible to do:
```php
use Parsecsv\PhpParseCsv\parseCSV;
...
$csv = new parseCSV('test.csv');
...
```
 But you are right, the namespace, that I set, is not very good.

**Comment by wareczek** [comment]
I like `\ParseCSV\Parser` idea. Please add namespace support.

**Comment by Fonata** [comment]
Unfortunately, this breaks compatibility with previous consumers of this library. PHPUnit and many other libraries have done it. Also, renaming the file to make auto-loading work, as in this fork: https://github.com/michaelsharman/parsecsv-for-php/commit/87d363d60549af4401bf68c77f7436c0de379852

It's on my agenda. PSR/Namespace/Composer/Autoloading is important to make this library stay relevant. 

I hate to break other people's stuff, and I know not everyone would read the release notes: but hey, this is a good reason to publish a release!

**Comment by SaintPeter** [comment]
I suggest you merge this as a major branch number change.  You can reference the prior branch for users who need non-namespace compatibility.  New users should use the namespacing.

**Comment by Fonata** [comment]
The purpose of a namespace is to avoid conflicts between e.g. classes with the same name. The name parseCSV is somewhat generic. Of which actual conflicts are you aware?

A namespace is not needed for the Composer autoloader. I am strongly against adding the namespace just for [PSR-4](https://www.php-fig.org/psr/psr-4/) compliance. I'm very open to practical considerations. Which practical benefits of a namespace do you see for a single-file library?

**Pull request closed without merging**
