### PR TITLE
_wfile return value was always true..

### PR DESCRIPTION
**Pull request by repat**
..whether or not *file_put_contents()* was successful

```This function returns the number of bytes that were written to the file, or FALSE on failure.```
-- https://php.net/manual/de/function.file-put-contents.php

### CODE REVIEW

**Comment by jimeh** [comment]
:+1:

**Comment by williamknauss** [comment]
@repat,
I ended up taking out the file put contents because it wasn't appending data to existing files...

**Comment by repat** [comment]
So this is not the uptodate code?

**Comment by repat** [comment]
Also, you can use ```FILE_APPEND``` as a flag to append to an existing file, see https://secure.php.net/manual/en/function.file-put-contents.php

**Pull request closed without merging**
