### PR TITLE
Fixes testing problems

### PR DESCRIPTION
**Pull request by susgo**

### CODE REVIEW

**Comment by susgo** [comment]
Should work now. See commit messages for more details about the bug

**Comment by Fonata** [comment]
Thanks for the quick solution! 

@susgo good you spotted the autoloading issue! I decided to drop PHP 5.4 support so I just cherry-picked 9395f0f26136f67431a7d7ff18c4344d97aff609 so close = merged here. I'll create a merge request in a few hours.

**Comment by susgo** [comment]
@Fonata Cool, I think that is the right decision. But as you already know, my vision goes even further. Again, feel free to go to the Drupal meeting today. You need this group more than I do.

**Comment by Fonata** [comment]
Thanks. I really won't go.

**Comment by susgo** [comment]
@Fonata Now I feel guilty. I can give all upcoming meetups free if this helps

**Comment by Fonata** [comment]
No need at all to feel that way, all is fine. You just mark those meetings as "I'm going" which interest you.

**Comment by susgo** [comment]
@Fonata Same for you. I will go into it - promise.

**Pull request closed without merging**
